language: php

jobs:
  fast_finish: true
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
      after_script:
        - bash <(curl -s https://codecov.io/bash)
    - php: 'nightly'
      install:
        - composer update --no-interaction --ignore-platform-reqs
    - php: '7.4'
      name: 'Prefer lowest'
      install:
        - composer update --prefer-lowest
    -  os: windows
       language: shell
       before_install:
         - choco install php --version 7.4
         - choco install composer
         - choco install com0com
         - export PATH="/c/tools/php74:/c/ProgramData/ComposerSetup/bin/:$PATH"
       cache:
         directories:
           - $LOCALAPPDATA/Composer/files
    - os: osx
      before_install:
        - brew install php
        - brew install composer

  allow_failures:
    - php: 'nightly'

cache:
  directories:
    - $HOME/.cache/composer/files

install:
  composer update --no-interaction

before_script:
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit
