language: php

jobs:
  fast_finish: true
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
      after_script:
        - bash <(curl -s https://codecov.io/bash)
    - php: 'nightly'
      install:
        - composer update --no-interaction --ignore-platform-reqs
    - php: '7.4'
      name: 'Prefer lowest'
      install:
        - composer update --prefer-lowest
    -  os: windows
       language: shell
       before_install:
         - choco install php --version 7.4
         - choco install composer
         - choco install com0com
         - export PATH="/c/tools/php74:/c/ProgramData/ComposerSetup/bin/:$PATH"
         - wget -O /c/tools/php74/ext/php_xdebug-3.0.0-7.4-vc15-nts-x86_64.dll https://xdebug.org/files/php_xdebug-3.0.0-7.4-vc15-nts-x86_64.dll
         - cp $TRAVIS_BUILD_DIR/tests/config/php_windows.ini /c/tools/php74/php.ini
       cache:
         directories:
           - $LOCALAPPDATA/Composer/files
       after_script:
         - bash <(curl -s https://codecov.io/bash)
    - os: osx
      language: shell
      osx_image: xcode12.2
      before_install:
        - export HOMEBREW_NO_AUTO_UPDATE=1
        - sh -c "mkdir -p ${TRAVIS_BUILD_DIR}/travis/module-cache/`php-config --vernum`"
        - chmod +x ./tests/modulecache.sh
        - git clone https://github.com/madumlao/phpenv.git ~/.phpenv
        - brew install re2c openssl bison libxml2 autoconf automake icu4c libjpeg libpng libmcrypt libzip
        - export PATH="/usr/local/opt/bison/bin:$PATH"
        - export PHPENV_ROOT="$HOME/.phpenv"
        - export PATH="$PHPENV_ROOT/bin:$PATH"
        - phpenv init -
        - phpenv install -l
        - phpenv install 7.3.7
        - phpenv rehash
      before_script:
        - MODULES="xdebug.so:xdebug" ./tests/modulecache.sh
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - ${TRAVIS_BUILD_DIR}/travis/module-cache
      before_cache:
        - brew cleanup
      after_script:
        - bash <(curl -s https://codecov.io/bash)

  allow_failures:
    - php: 'nightly'

cache:
  directories:
    - $HOME/.cache/composer/files

install:
  composer update --no-interaction

before_script:
 - vendor/bin/phpunit --version

script:
 - sudo vendor/bin/phpunit
